import React from 'react';
import {
  Plane,
  Building2,
  Compass,
  FileCheck2,
  GraduationCap,
  Building,
  ShoppingBag,
  Briefcase,
  Sparkles,
  Smartphone,
  TrendingUp,
  BarChart3,
  Heart,
  Moon,
  UserCheck,
  Network,
  Crown,
  Palette,
  FileText,
  Target,
  Calculator,
  Users,
  ShieldCheck,
  Code2,
  Globe,
  Bot,
  User,
  LucideIcon,
} from 'lucide-react';
import { MainViewModule, PortalType } from '../types';

export interface EcosystemPortalItem {
  id: number;
  module: MainViewModule;
  label: string;
  shortLabel?: string;
  category: 'Core Travel & OTA' | 'Global Mobility & Services' | 'AI & Digital Platforms' | 'Enterprise Operations';
  description: string;
  icon: LucideIcon;
  badge?: string;
  badgeColor?: string;
  hash: string;
}

export const ECOSYSTEM_PORTALS: EcosystemPortalItem[] = [
  {
    id: 1,
    module: 'flights',
    label: 'Flight Search',
    shortLabel: 'Flights',
    category: 'Core Travel & OTA',
    description: 'Sabre, Amadeus & Galileo live GDS fare search and instant ticketing',
    icon: Plane,
    badge: 'Multi-GDS',
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    hash: 'flights',
  },
  {
    id: 2,
    module: 'hotels',
    label: 'Halal Hotels',
    shortLabel: 'Hotels',
    category: 'Core Travel & OTA',
    description: 'Halal-friendly certified global accommodations & luxury resorts',
    icon: Building2,
    badge: 'Halal Verified',
    badgeColor: 'bg-amber-100 text-amber-800 border-amber-300',
    hash: 'hotels',
  },
  {
    id: 3,
    module: 'packages',
    label: 'Tour Packages & Umrah',
    shortLabel: 'Packages',
    category: 'Core Travel & OTA',
    description: 'Curated international holidays, domestic tours & executive packages',
    icon: Compass,
    badge: 'Featured',
    badgeColor: 'bg-blue-100 text-blue-800 border-blue-300',
    hash: 'packages',
  },
  {
    id: 4,
    module: 'visa',
    label: 'Visa Portal',
    shortLabel: 'Visa',
    category: 'Global Mobility & Services',
    description: 'Online visa requirements, document checklist & live tracking',
    icon: FileCheck2,
    badge: '99.2% Success',
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    hash: 'visa',
  },
  {
    id: 5,
    module: 'study-abroad',
    label: 'Study Abroad',
    shortLabel: 'Study Abroad',
    category: 'Global Mobility & Services',
    description: '500+ Partner universities in UK, Canada, Australia, USA & Malaysia',
    icon: GraduationCap,
    badge: '500+ Universities',
    badgeColor: 'bg-purple-100 text-purple-800 border-purple-300',
    hash: 'study-abroad',
  },
  {
    id: 6,
    module: 'business-units',
    label: 'JEL Business Units',
    shortLabel: 'Business Units',
    category: 'Global Mobility & Services',
    description: '14 Specialized enterprise divisions & strategic subsidiaries',
    icon: Building,
    badge: '14 Divisions',
    badgeColor: 'bg-slate-100 text-slate-800 border-slate-300',
    hash: 'business-units',
  },
  {
    id: 7,
    module: 'craft-bangla',
    label: 'Craft Bangla',
    shortLabel: 'Craft Bangla',
    category: 'Global Mobility & Services',
    description: 'Heritage marketplace for authentic Muslin, Jamdani & artisanal crafts',
    icon: ShoppingBag,
    badge: 'Artisanal',
    badgeColor: 'bg-rose-100 text-rose-800 border-rose-300',
    hash: 'craft-bangla',
  },
  {
    id: 8,
    module: 'corporate',
    label: 'Corporate',
    shortLabel: 'Corporate',
    category: 'Global Mobility & Services',
    description: 'Enterprise corporate travel management, policies & credit line',
    icon: Briefcase,
    badge: 'B2B Pro',
    badgeColor: 'bg-indigo-100 text-indigo-800 border-indigo-300',
    hash: 'corporate',
  },
  {
    id: 9,
    module: 'ai-engine',
    label: 'AI Engine',
    shortLabel: 'AI Engine',
    category: 'AI & Digital Platforms',
    description: 'Gemini AI itinerary planner, visa advisor & predictive pricing',
    icon: Sparkles,
    badge: 'Gemini AI',
    badgeColor: 'bg-amber-100 text-amber-800 border-amber-300',
    hash: 'ai-engine',
  },
  {
    id: 10,
    module: 'mobile',
    label: 'Mobile Apps',
    shortLabel: 'Mobile Apps',
    category: 'AI & Digital Platforms',
    description: 'iOS & Android Super App architecture with offline boarding passes',
    icon: Smartphone,
    badge: 'iOS / Android',
    badgeColor: 'bg-cyan-100 text-cyan-800 border-cyan-300',
    hash: 'mobile',
  },
  {
    id: 11,
    module: 'growth-seo',
    label: 'SEO & Growth',
    shortLabel: 'SEO & Growth',
    category: 'AI & Digital Platforms',
    description: 'International travel SEO, Schema.org rich snippets & organic growth engine',
    icon: TrendingUp,
    badge: '100 Score',
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    hash: 'growth-seo',
  },
  {
    id: 12,
    module: 'bi-analytics',
    label: 'BI & Analytics',
    shortLabel: 'BI Analytics',
    category: 'AI & Digital Platforms',
    description: 'Real-time revenue telemetry, conversion funnels & GDS query metrics',
    icon: BarChart3,
    badge: 'Telemetry',
    badgeColor: 'bg-blue-100 text-blue-800 border-blue-300',
    hash: 'bi-analytics',
  },
  {
    id: 13,
    module: 'healthcare',
    label: 'Healthcare & Insurance',
    shortLabel: 'Healthcare',
    category: 'Global Mobility & Services',
    description: 'Global travel medical insurance, overseas health packages & wellness',
    icon: Heart,
    badge: 'Covered',
    badgeColor: 'bg-red-100 text-red-800 border-red-300',
    hash: 'healthcare',
  },
  {
    id: 14,
    module: 'hajj-umrah',
    label: 'Hajj & Umrah',
    shortLabel: 'Hajj & Umrah',
    category: 'Global Mobility & Services',
    description: 'VIP 5-star Makkah & Madinah packages, Nusuk visa support & ziyarah',
    icon: Moon,
    badge: 'Executive',
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    hash: 'hajj-umrah',
  },
  {
    id: 15,
    module: 'concierge',
    label: 'Meet & Greet',
    shortLabel: 'Meet & Greet',
    category: 'Global Mobility & Services',
    description: 'Hazrat Shahjalal Int Airport VIP fast-track, lounge & chauffeur service',
    icon: UserCheck,
    badge: 'VIP Service',
    badgeColor: 'bg-amber-100 text-amber-800 border-amber-300',
    hash: 'concierge',
  },
  {
    id: 16,
    module: 'dmc-marketplace',
    label: 'DMC Marketplace',
    shortLabel: 'DMC Market',
    category: 'Enterprise Operations',
    description: 'Direct supplier contracting, local destination managers & wholesale rates',
    icon: Globe,
    badge: 'Wholesale',
    badgeColor: 'bg-teal-100 text-teal-800 border-teal-300',
    hash: 'dmc-marketplace',
  },
  {
    id: 17,
    module: 'api-gateway',
    label: 'API Gateway & Hub',
    shortLabel: 'API Gateway',
    category: 'AI & Digital Platforms',
    description: 'High-throughput enterprise REST/GraphQL middleware & rate limiting',
    icon: Network,
    badge: 'Developer Hub',
    badgeColor: 'bg-violet-100 text-violet-800 border-violet-300',
    hash: 'api-gateway',
  },
  {
    id: 18,
    module: 'customer-loyalty',
    label: 'Customer 360 & Loyalty',
    shortLabel: 'Loyalty 360',
    category: 'Enterprise Operations',
    description: 'Tiered frequent flyer club, JEL reward points & lifetime value CRM',
    icon: Crown,
    badge: 'VIP Club',
    badgeColor: 'bg-yellow-100 text-yellow-800 border-yellow-300',
    hash: 'customer-loyalty',
  },
  {
    id: 19,
    module: 'enterprise-design-system',
    label: 'Website & Design System',
    shortLabel: 'Design System',
    category: 'AI & Digital Platforms',
    description: 'Luxury design tokens, UI component library & brand specifications',
    icon: Palette,
    badge: 'Design Kit',
    badgeColor: 'bg-pink-100 text-pink-800 border-pink-300',
    hash: 'enterprise-design-system',
  },
  {
    id: 20,
    module: 'enterprise-cms',
    label: 'Headless CMS & Knowledge',
    shortLabel: 'Headless CMS',
    category: 'Enterprise Operations',
    description: 'Omnichannel content publishing, destination guides & travel advisories',
    icon: FileText,
    badge: 'Knowledge Hub',
    badgeColor: 'bg-indigo-100 text-indigo-800 border-indigo-300',
    hash: 'enterprise-cms',
  },
  {
    id: 21,
    module: 'crm-sales',
    label: 'CRM & Sales Automation',
    shortLabel: 'CRM & Sales',
    category: 'Enterprise Operations',
    description: 'Automated lead qualification, WhatsApp bot pipelines & agent assignment',
    icon: Target,
    badge: 'Pipeline AI',
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    hash: 'crm-sales',
  },
  {
    id: 22,
    module: 'erp-finance',
    label: 'ERP & Finance Operations',
    shortLabel: 'ERP & Finance',
    category: 'Enterprise Operations',
    description: 'Double-entry ledger, multi-currency invoicing, bKash & card reconciliation',
    icon: Calculator,
    badge: 'Accounting',
    badgeColor: 'bg-blue-100 text-blue-800 border-blue-300',
    hash: 'erp-finance',
  },
  {
    id: 23,
    module: 'hr-management',
    label: 'HRMS & Employee Intelligence',
    shortLabel: 'HRMS Portal',
    category: 'Enterprise Operations',
    description: 'Staff directory, commission payouts, performance KPIs & training',
    icon: Users,
    badge: 'Workforce',
    badgeColor: 'bg-slate-100 text-slate-800 border-slate-300',
    hash: 'hr-management',
  },
];

export interface SystemPortalOption {
  id: PortalType;
  title: string;
  subtitle: string;
  icon: LucideIcon;
  colorClass: string;
}

export const SYSTEM_PORTALS: SystemPortalOption[] = [
  {
    id: 'main',
    title: 'Main OTA Platform',
    subtitle: 'Public flights, hotels, visa & 23 ecosystem portals',
    icon: Globe,
    colorClass: 'text-[#0B6B53] bg-[#0B6B53]/10',
  },
  {
    id: 'customer',
    title: 'Customer Portal',
    subtitle: 'Bookings, e-tickets, passport docs & JEL wallet',
    icon: User,
    colorClass: 'text-[#C7A44D] bg-[#C7A44D]/10',
  },
  {
    id: 'agent',
    title: 'B2B Agent Portal',
    subtitle: 'GDS issuance, wholesale rates & credit line management',
    icon: Briefcase,
    colorClass: 'text-[#093F31] bg-[#093F31]/10',
  },
  {
    id: 'admin',
    title: 'Admin Control Center',
    subtitle: 'Executive telemetry, GDS feeds, CRM & payment ledger',
    icon: ShieldCheck,
    colorClass: 'text-[#0B6B53] bg-[#0B6B53]/10',
  },
  {
    id: 'architecture',
    title: 'Enterprise Architecture',
    subtitle: 'PostgreSQL schema, REST/GraphQL APIs & security specs',
    icon: Code2,
    colorClass: 'text-purple-600 bg-purple-50',
  },
];

export const PORTAL_CATEGORIES = [
  'All Portals',
  'Core Travel & OTA',
  'Global Mobility & Services',
  'AI & Digital Platforms',
  'Enterprise Operations',
] as const;
