export interface DestinationPoint {
  id: string;
  name: string;
  country: string;
  code: string;
  lat: number;
  lng: number;
  category: 'Study' | 'Travel' | 'Hajj & Umrah' | 'Business' | 'Global Mobility';
  flightHoursFromDhaka: string;
  visaType: string;
  description: string;
  color: string;
}

export const GLOBAL_DESTINATIONS: DestinationPoint[] = [
  {
    id: 'dac',
    name: 'Dhaka',
    country: 'Bangladesh',
    code: 'DAC',
    lat: 23.8103,
    lng: 90.4125,
    category: 'Global Mobility',
    flightHoursFromDhaka: 'Origin Hub',
    visaType: 'Domestic Headquarters',
    description: 'Central Aviation & AI Intelligence Operations Hub of Journey Expert Limited.',
    color: '#10B981',
  },
  {
    id: 'lhr',
    name: 'London',
    country: 'United Kingdom',
    code: 'LHR',
    lat: 51.5074,
    lng: -0.1278,
    category: 'Study',
    flightHoursFromDhaka: '10h 30m direct',
    visaType: 'Student Route & Standard Visitor',
    description: 'Top destination for UK Russell Group universities, corporate finance, and European transit.',
    color: '#38BDF8',
  },
  {
    id: 'yyz',
    name: 'Toronto',
    country: 'Canada',
    code: 'YYZ',
    lat: 43.6532,
    lng: -79.3832,
    category: 'Global Mobility',
    flightHoursFromDhaka: '16h 45m (1 stop)',
    visaType: 'Study Permit & Express Entry Support',
    description: 'Leading global mobility hub with world-class universities and permanent residency pathways.',
    color: '#F43F5E',
  },
  {
    id: 'dxb',
    name: 'Dubai',
    country: 'United Arab Emirates',
    code: 'DXB',
    lat: 25.2048,
    lng: 55.2708,
    category: 'Travel',
    flightHoursFromDhaka: '5h 15m direct',
    visaType: '30/60 Days E-Visa Instant',
    description: 'Luxury shopping, global corporate expos, world-class theme parks and middle-east flight transit.',
    color: '#F59E0B',
  },
  {
    id: 'mel',
    name: 'Melbourne',
    country: 'Australia',
    code: 'MEL',
    lat: -37.8136,
    lng: 144.9631,
    category: 'Study',
    flightHoursFromDhaka: '13h 20m (1 stop)',
    visaType: 'Subclass 500 Student & Subclass 600',
    description: 'Australia’s cultural capital featuring prestigious Group of Eight university admissions.',
    color: '#818CF8',
  },
  {
    id: 'syd',
    name: 'Sydney',
    country: 'Australia',
    code: 'SYD',
    lat: -33.8688,
    lng: 151.2093,
    category: 'Study',
    flightHoursFromDhaka: '13h 45m (1 stop)',
    visaType: 'Subclass 500 Student & Visitor Visa',
    description: 'Iconic harbor destination, leading academic research centers, and global commerce hub.',
    color: '#6366F1',
  },
  {
    id: 'cul',
    name: 'Kuala Lumpur',
    country: 'Malaysia',
    code: 'KUL',
    lat: 3.139,
    lng: 101.6869,
    category: 'Travel',
    flightHoursFromDhaka: '3h 45m direct',
    visaType: 'MDAC E-Visa & EMGS Student Pass',
    description: 'Affordable quality higher education, medical tourism, and tropical Southeast Asian holidays.',
    color: '#EC4899',
  },
  {
    id: 'sin',
    name: 'Singapore',
    country: 'Singapore',
    code: 'SIN',
    lat: 1.3521,
    lng: 103.8198,
    category: 'Business',
    flightHoursFromDhaka: '4h 00m direct',
    visaType: 'SG Arrival Card & Business Visa',
    description: 'Asia’s premier financial hub, medical center, and Changi Jewel aviation gateway.',
    color: '#06B6D4',
  },
  {
    id: 'ist',
    name: 'Istanbul',
    country: 'Turkey',
    code: 'IST',
    lat: 41.0082,
    lng: 28.9784,
    category: 'Travel',
    flightHoursFromDhaka: '7h 50m direct',
    visaType: 'Turkish Sticker & E-Visa',
    description: 'Historic crossroads of East and West, medical hair transplant hub, and Turkish Airlines mega-hub.',
    color: '#EAB308',
  },
  {
    id: 'jed',
    name: 'Jeddah & Makkah',
    country: 'Saudi Arabia',
    code: 'JED',
    lat: 21.4858,
    lng: 39.1925,
    category: 'Hajj & Umrah',
    flightHoursFromDhaka: '6h 30m direct',
    visaType: 'Nusuk Umrah & Tourist E-Visa',
    description: 'Gateway to the Holy Harams with executive VIP clock-tower hotels and guided Ziyarat packages.',
    color: '#C8A14A',
  },
  {
    id: 'ruh',
    name: 'Riyadh',
    country: 'Saudi Arabia',
    code: 'RUH',
    lat: 24.7136,
    lng: 46.6753,
    category: 'Business',
    flightHoursFromDhaka: '6h 00m direct',
    visaType: 'Business & Tourist E-Visa',
    description: 'Dynamic GCC economic capital, mega-infrastructure projects, and Saudi Vision 2030 hub.',
    color: '#14B8A6',
  },
  {
    id: 'jfk',
    name: 'New York',
    country: 'United States',
    code: 'JFK',
    lat: 40.7128,
    lng: -74.006,
    category: 'Study',
    flightHoursFromDhaka: '18h 30m (1 stop)',
    visaType: 'F-1 Student & B1/B2 Visitor',
    description: 'Ivy League academic ecosystem, Wall Street finance, and premier global transit hub.',
    color: '#3B82F6',
  },
];
